/*
 * This file is generated by jOOQ.
 */
package com.xzh.myresrc.base.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * 数据字典表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysDict implements Serializable {

    private static final long serialVersionUID = -1489292495;

    private Long    id;
    private String  name;
    private String  type;
    private String  code;
    private String  value;
    private Integer orderNum;
    private String  remark;
    private Integer delFlag;

    public SysDict() {}

    public SysDict(SysDict value) {
        this.id = value.id;
        this.name = value.name;
        this.type = value.type;
        this.code = value.code;
        this.value = value.value;
        this.orderNum = value.orderNum;
        this.remark = value.remark;
        this.delFlag = value.delFlag;
    }

    public SysDict(
        Long    id,
        String  name,
        String  type,
        String  code,
        String  value,
        Integer orderNum,
        String  remark,
        Integer delFlag
    ) {
        this.id = id;
        this.name = name;
        this.type = type;
        this.code = code;
        this.value = value;
        this.orderNum = orderNum;
        this.remark = remark;
        this.delFlag = delFlag;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public Integer getOrderNum() {
        return this.orderNum;
    }

    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public Integer getDelFlag() {
        return this.delFlag;
    }

    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SysDict (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(type);
        sb.append(", ").append(code);
        sb.append(", ").append(value);
        sb.append(", ").append(orderNum);
        sb.append(", ").append(remark);
        sb.append(", ").append(delFlag);

        sb.append(")");
        return sb.toString();
    }
}
