#backup
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/myresrc_admin?useUnicode=true&characterEncoding=UTF8
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
server:
  port: 8001