/*
 * This file is generated by jOOQ.
 */
package com.xzh.myresrc.base.db.tables.records;


import com.xzh.myresrc.base.db.tables.SysDict;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 数据字典表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysDictRecord extends UpdatableRecordImpl<SysDictRecord> implements Record8<Long, String, String, String, String, Integer, String, Integer> {

    private static final long serialVersionUID = 1089485233;

    /**
     * Setter for <code>myresrc_base.sys_dict.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>myresrc_base.sys_dict.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>myresrc_base.sys_dict.name</code>. 字典名称
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>myresrc_base.sys_dict.name</code>. 字典名称
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>myresrc_base.sys_dict.type</code>. 字典类型
     */
    public void setType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>myresrc_base.sys_dict.type</code>. 字典类型
     */
    public String getType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>myresrc_base.sys_dict.code</code>. 字典码
     */
    public void setCode(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>myresrc_base.sys_dict.code</code>. 字典码
     */
    public String getCode() {
        return (String) get(3);
    }

    /**
     * Setter for <code>myresrc_base.sys_dict.value</code>. 字典值
     */
    public void setValue(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>myresrc_base.sys_dict.value</code>. 字典值
     */
    public String getValue() {
        return (String) get(4);
    }

    /**
     * Setter for <code>myresrc_base.sys_dict.order_num</code>. 排序
     */
    public void setOrderNum(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>myresrc_base.sys_dict.order_num</code>. 排序
     */
    public Integer getOrderNum() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>myresrc_base.sys_dict.remark</code>. 备注
     */
    public void setRemark(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>myresrc_base.sys_dict.remark</code>. 备注
     */
    public String getRemark() {
        return (String) get(6);
    }

    /**
     * Setter for <code>myresrc_base.sys_dict.del_flag</code>. 删除标记  -1：已删除  0：正常
     */
    public void setDelFlag(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>myresrc_base.sys_dict.del_flag</code>. 删除标记  -1：已删除  0：正常
     */
    public Integer getDelFlag() {
        return (Integer) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, String, String, String, String, Integer, String, Integer> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, String, String, String, String, Integer, String, Integer> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return SysDict.SYS_DICT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return SysDict.SYS_DICT.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return SysDict.SYS_DICT.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return SysDict.SYS_DICT.CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return SysDict.SYS_DICT.VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return SysDict.SYS_DICT.ORDER_NUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return SysDict.SYS_DICT.REMARK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return SysDict.SYS_DICT.DEL_FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getOrderNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getDelFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getOrderNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getDelFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysDictRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysDictRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysDictRecord value3(String value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysDictRecord value4(String value) {
        setCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysDictRecord value5(String value) {
        setValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysDictRecord value6(Integer value) {
        setOrderNum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysDictRecord value7(String value) {
        setRemark(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysDictRecord value8(Integer value) {
        setDelFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysDictRecord values(Long value1, String value2, String value3, String value4, String value5, Integer value6, String value7, Integer value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysDictRecord
     */
    public SysDictRecord() {
        super(SysDict.SYS_DICT);
    }

    /**
     * Create a detached, initialised SysDictRecord
     */
    public SysDictRecord(Long id, String name, String type, String code, String value, Integer orderNum, String remark, Integer delFlag) {
        super(SysDict.SYS_DICT);

        set(0, id);
        set(1, name);
        set(2, type);
        set(3, code);
        set(4, value);
        set(5, orderNum);
        set(6, remark);
        set(7, delFlag);
    }
}
