/*
 * This file is generated by jOOQ.
 */
package com.xzh.myresrc.admin.db;


import com.xzh.myresrc.admin.db.tables.SysLog;
import com.xzh.myresrc.admin.db.tables.SysMenu;
import com.xzh.myresrc.admin.db.tables.SysRole;
import com.xzh.myresrc.admin.db.tables.SysRoleMenu;
import com.xzh.myresrc.admin.db.tables.SysUser;
import com.xzh.myresrc.admin.db.tables.SysUserRole;
import com.xzh.myresrc.admin.db.tables.SysUserToken;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>myresrc_admin</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index SYS_LOG_PRIMARY = Indexes0.SYS_LOG_PRIMARY;
    public static final Index SYS_MENU_PRIMARY = Indexes0.SYS_MENU_PRIMARY;
    public static final Index SYS_ROLE_PRIMARY = Indexes0.SYS_ROLE_PRIMARY;
    public static final Index SYS_ROLE_MENU_PRIMARY = Indexes0.SYS_ROLE_MENU_PRIMARY;
    public static final Index SYS_USER_PRIMARY = Indexes0.SYS_USER_PRIMARY;
    public static final Index SYS_USER_USERNAME = Indexes0.SYS_USER_USERNAME;
    public static final Index SYS_USER_ROLE_PRIMARY = Indexes0.SYS_USER_ROLE_PRIMARY;
    public static final Index SYS_USER_TOKEN_PRIMARY = Indexes0.SYS_USER_TOKEN_PRIMARY;
    public static final Index SYS_USER_TOKEN_TOKEN = Indexes0.SYS_USER_TOKEN_TOKEN;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index SYS_LOG_PRIMARY = Internal.createIndex("PRIMARY", SysLog.SYS_LOG, new OrderField[] { SysLog.SYS_LOG.ID }, true);
        public static Index SYS_MENU_PRIMARY = Internal.createIndex("PRIMARY", SysMenu.SYS_MENU, new OrderField[] { SysMenu.SYS_MENU.MENU_ID }, true);
        public static Index SYS_ROLE_PRIMARY = Internal.createIndex("PRIMARY", SysRole.SYS_ROLE, new OrderField[] { SysRole.SYS_ROLE.ROLE_ID }, true);
        public static Index SYS_ROLE_MENU_PRIMARY = Internal.createIndex("PRIMARY", SysRoleMenu.SYS_ROLE_MENU, new OrderField[] { SysRoleMenu.SYS_ROLE_MENU.ID }, true);
        public static Index SYS_USER_PRIMARY = Internal.createIndex("PRIMARY", SysUser.SYS_USER, new OrderField[] { SysUser.SYS_USER.USER_ID }, true);
        public static Index SYS_USER_USERNAME = Internal.createIndex("username", SysUser.SYS_USER, new OrderField[] { SysUser.SYS_USER.USERNAME }, true);
        public static Index SYS_USER_ROLE_PRIMARY = Internal.createIndex("PRIMARY", SysUserRole.SYS_USER_ROLE, new OrderField[] { SysUserRole.SYS_USER_ROLE.ID }, true);
        public static Index SYS_USER_TOKEN_PRIMARY = Internal.createIndex("PRIMARY", SysUserToken.SYS_USER_TOKEN, new OrderField[] { SysUserToken.SYS_USER_TOKEN.USER_ID }, true);
        public static Index SYS_USER_TOKEN_TOKEN = Internal.createIndex("token", SysUserToken.SYS_USER_TOKEN, new OrderField[] { SysUserToken.SYS_USER_TOKEN.TOKEN }, true);
    }
}
