/*
 * This file is generated by jOOQ.
 */
package com.xzh.myresrc.admin.db;


import com.xzh.myresrc.admin.db.tables.SysLog;
import com.xzh.myresrc.admin.db.tables.SysMenu;
import com.xzh.myresrc.admin.db.tables.SysRole;
import com.xzh.myresrc.admin.db.tables.SysRoleMenu;
import com.xzh.myresrc.admin.db.tables.SysUser;
import com.xzh.myresrc.admin.db.tables.SysUserRole;
import com.xzh.myresrc.admin.db.tables.SysUserToken;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MyresrcAdmin extends SchemaImpl {

    private static final long serialVersionUID = -985493302;

    /**
     * The reference instance of <code>myresrc_admin</code>
     */
    public static final MyresrcAdmin MYRESRC_ADMIN = new MyresrcAdmin();

    /**
     * 系统日志
     */
    public final SysLog SYS_LOG = com.xzh.myresrc.admin.db.tables.SysLog.SYS_LOG;

    /**
     * 菜单管理
     */
    public final SysMenu SYS_MENU = com.xzh.myresrc.admin.db.tables.SysMenu.SYS_MENU;

    /**
     * 角色
     */
    public final SysRole SYS_ROLE = com.xzh.myresrc.admin.db.tables.SysRole.SYS_ROLE;

    /**
     * 角色与菜单对应关系
     */
    public final SysRoleMenu SYS_ROLE_MENU = com.xzh.myresrc.admin.db.tables.SysRoleMenu.SYS_ROLE_MENU;

    /**
     * 系统用户
     */
    public final SysUser SYS_USER = com.xzh.myresrc.admin.db.tables.SysUser.SYS_USER;

    /**
     * 用户与角色对应关系
     */
    public final SysUserRole SYS_USER_ROLE = com.xzh.myresrc.admin.db.tables.SysUserRole.SYS_USER_ROLE;

    /**
     * 系统用户Token
     */
    public final SysUserToken SYS_USER_TOKEN = com.xzh.myresrc.admin.db.tables.SysUserToken.SYS_USER_TOKEN;

    /**
     * No further instances allowed
     */
    private MyresrcAdmin() {
        super("myresrc_admin", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            SysLog.SYS_LOG,
            SysMenu.SYS_MENU,
            SysRole.SYS_ROLE,
            SysRoleMenu.SYS_ROLE_MENU,
            SysUser.SYS_USER,
            SysUserRole.SYS_USER_ROLE,
            SysUserToken.SYS_USER_TOKEN);
    }
}
