/*
 * This file is generated by jOOQ.
 */
package com.xzh.myresrc.base.db;


import com.xzh.myresrc.base.db.tables.SysDict;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>myresrc_base</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index SYS_DICT_PRIMARY = Indexes0.SYS_DICT_PRIMARY;
    public static final Index SYS_DICT_TYPE = Indexes0.SYS_DICT_TYPE;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index SYS_DICT_PRIMARY = Internal.createIndex("PRIMARY", SysDict.SYS_DICT, new OrderField[] { SysDict.SYS_DICT.ID }, true);
        public static Index SYS_DICT_TYPE = Internal.createIndex("type", SysDict.SYS_DICT, new OrderField[] { SysDict.SYS_DICT.TYPE, SysDict.SYS_DICT.CODE }, true);
    }
}
