/*
 * This file is generated by jOOQ.
 */
package com.xzh.myresrc.base.db;


import com.xzh.myresrc.base.db.tables.SysDict;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in myresrc_base
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * 数据字典表
     */
    public static final SysDict SYS_DICT = com.xzh.myresrc.base.db.tables.SysDict.SYS_DICT;
}
