/*
 * This file is generated by jOOQ.
 */
package com.xzh.myresrc.admin.db.tables.daos;


import com.xzh.myresrc.admin.db.tables.SysLog;
import com.xzh.myresrc.admin.db.tables.records.SysLogRecord;

import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * 系统日志
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class SysLogDao extends DAOImpl<SysLogRecord, com.xzh.myresrc.admin.db.tables.pojos.SysLog, Long> {

    /**
     * Create a new SysLogDao without any configuration
     */
    public SysLogDao() {
        super(SysLog.SYS_LOG, com.xzh.myresrc.admin.db.tables.pojos.SysLog.class);
    }

    /**
     * Create a new SysLogDao with an attached configuration
     */
    @Autowired
    public SysLogDao(Configuration configuration) {
        super(SysLog.SYS_LOG, com.xzh.myresrc.admin.db.tables.pojos.SysLog.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(com.xzh.myresrc.admin.db.tables.pojos.SysLog object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.xzh.myresrc.admin.db.tables.pojos.SysLog> fetchById(Long... values) {
        return fetch(SysLog.SYS_LOG.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.xzh.myresrc.admin.db.tables.pojos.SysLog fetchOneById(Long value) {
        return fetchOne(SysLog.SYS_LOG.ID, value);
    }

    /**
     * Fetch records that have <code>username IN (values)</code>
     */
    public List<com.xzh.myresrc.admin.db.tables.pojos.SysLog> fetchByUsername(String... values) {
        return fetch(SysLog.SYS_LOG.USERNAME, values);
    }

    /**
     * Fetch records that have <code>operation IN (values)</code>
     */
    public List<com.xzh.myresrc.admin.db.tables.pojos.SysLog> fetchByOperation(String... values) {
        return fetch(SysLog.SYS_LOG.OPERATION, values);
    }

    /**
     * Fetch records that have <code>method IN (values)</code>
     */
    public List<com.xzh.myresrc.admin.db.tables.pojos.SysLog> fetchByMethod(String... values) {
        return fetch(SysLog.SYS_LOG.METHOD, values);
    }

    /**
     * Fetch records that have <code>params IN (values)</code>
     */
    public List<com.xzh.myresrc.admin.db.tables.pojos.SysLog> fetchByParams(String... values) {
        return fetch(SysLog.SYS_LOG.PARAMS, values);
    }

    /**
     * Fetch records that have <code>time IN (values)</code>
     */
    public List<com.xzh.myresrc.admin.db.tables.pojos.SysLog> fetchByTime(Long... values) {
        return fetch(SysLog.SYS_LOG.TIME, values);
    }

    /**
     * Fetch records that have <code>ip IN (values)</code>
     */
    public List<com.xzh.myresrc.admin.db.tables.pojos.SysLog> fetchByIp(String... values) {
        return fetch(SysLog.SYS_LOG.IP, values);
    }

    /**
     * Fetch records that have <code>create_date IN (values)</code>
     */
    public List<com.xzh.myresrc.admin.db.tables.pojos.SysLog> fetchByCreateDate(LocalDateTime... values) {
        return fetch(SysLog.SYS_LOG.CREATE_DATE, values);
    }
}
