/*
 * This file is generated by jOOQ.
 */
package com.xzh.myresrc.admin.db.tables.daos;


import com.xzh.myresrc.admin.db.tables.SysMenu;
import com.xzh.myresrc.admin.db.tables.records.SysMenuRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * 菜单管理
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class SysMenuDao extends DAOImpl<SysMenuRecord, com.xzh.myresrc.admin.db.tables.pojos.SysMenu, Long> {

    /**
     * Create a new SysMenuDao without any configuration
     */
    public SysMenuDao() {
        super(SysMenu.SYS_MENU, com.xzh.myresrc.admin.db.tables.pojos.SysMenu.class);
    }

    /**
     * Create a new SysMenuDao with an attached configuration
     */
    @Autowired
    public SysMenuDao(Configuration configuration) {
        super(SysMenu.SYS_MENU, com.xzh.myresrc.admin.db.tables.pojos.SysMenu.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(com.xzh.myresrc.admin.db.tables.pojos.SysMenu object) {
        return object.getMenuId();
    }

    /**
     * Fetch records that have <code>menu_id IN (values)</code>
     */
    public List<com.xzh.myresrc.admin.db.tables.pojos.SysMenu> fetchByMenuId(Long... values) {
        return fetch(SysMenu.SYS_MENU.MENU_ID, values);
    }

    /**
     * Fetch a unique record that has <code>menu_id = value</code>
     */
    public com.xzh.myresrc.admin.db.tables.pojos.SysMenu fetchOneByMenuId(Long value) {
        return fetchOne(SysMenu.SYS_MENU.MENU_ID, value);
    }

    /**
     * Fetch records that have <code>parent_id IN (values)</code>
     */
    public List<com.xzh.myresrc.admin.db.tables.pojos.SysMenu> fetchByParentId(Long... values) {
        return fetch(SysMenu.SYS_MENU.PARENT_ID, values);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.xzh.myresrc.admin.db.tables.pojos.SysMenu> fetchByName(String... values) {
        return fetch(SysMenu.SYS_MENU.NAME, values);
    }

    /**
     * Fetch records that have <code>url IN (values)</code>
     */
    public List<com.xzh.myresrc.admin.db.tables.pojos.SysMenu> fetchByUrl(String... values) {
        return fetch(SysMenu.SYS_MENU.URL, values);
    }

    /**
     * Fetch records that have <code>perms IN (values)</code>
     */
    public List<com.xzh.myresrc.admin.db.tables.pojos.SysMenu> fetchByPerms(String... values) {
        return fetch(SysMenu.SYS_MENU.PERMS, values);
    }

    /**
     * Fetch records that have <code>type IN (values)</code>
     */
    public List<com.xzh.myresrc.admin.db.tables.pojos.SysMenu> fetchByType(Integer... values) {
        return fetch(SysMenu.SYS_MENU.TYPE, values);
    }

    /**
     * Fetch records that have <code>icon IN (values)</code>
     */
    public List<com.xzh.myresrc.admin.db.tables.pojos.SysMenu> fetchByIcon(String... values) {
        return fetch(SysMenu.SYS_MENU.ICON, values);
    }

    /**
     * Fetch records that have <code>order_num IN (values)</code>
     */
    public List<com.xzh.myresrc.admin.db.tables.pojos.SysMenu> fetchByOrderNum(Integer... values) {
        return fetch(SysMenu.SYS_MENU.ORDER_NUM, values);
    }
}
