/*
 * This file is generated by jOOQ.
 */
package com.xzh.myresrc.admin.db.tables.daos;


import com.xzh.myresrc.admin.db.tables.SysUserRole;
import com.xzh.myresrc.admin.db.tables.records.SysUserRoleRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * 用户与角色对应关系
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class SysUserRoleDao extends DAOImpl<SysUserRoleRecord, com.xzh.myresrc.admin.db.tables.pojos.SysUserRole, Long> {

    /**
     * Create a new SysUserRoleDao without any configuration
     */
    public SysUserRoleDao() {
        super(SysUserRole.SYS_USER_ROLE, com.xzh.myresrc.admin.db.tables.pojos.SysUserRole.class);
    }

    /**
     * Create a new SysUserRoleDao with an attached configuration
     */
    @Autowired
    public SysUserRoleDao(Configuration configuration) {
        super(SysUserRole.SYS_USER_ROLE, com.xzh.myresrc.admin.db.tables.pojos.SysUserRole.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(com.xzh.myresrc.admin.db.tables.pojos.SysUserRole object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.xzh.myresrc.admin.db.tables.pojos.SysUserRole> fetchById(Long... values) {
        return fetch(SysUserRole.SYS_USER_ROLE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.xzh.myresrc.admin.db.tables.pojos.SysUserRole fetchOneById(Long value) {
        return fetchOne(SysUserRole.SYS_USER_ROLE.ID, value);
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<com.xzh.myresrc.admin.db.tables.pojos.SysUserRole> fetchByUserId(Long... values) {
        return fetch(SysUserRole.SYS_USER_ROLE.USER_ID, values);
    }

    /**
     * Fetch records that have <code>role_id IN (values)</code>
     */
    public List<com.xzh.myresrc.admin.db.tables.pojos.SysUserRole> fetchByRoleId(Long... values) {
        return fetch(SysUserRole.SYS_USER_ROLE.ROLE_ID, values);
    }
}
