/*
 * This file is generated by jOOQ.
 */
package com.xzh.myresrc.admin.db.tables.daos;


import com.xzh.myresrc.admin.db.tables.SysUser;
import com.xzh.myresrc.admin.db.tables.records.SysUserRecord;

import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * 系统用户
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class SysUserDao extends DAOImpl<SysUserRecord, com.xzh.myresrc.admin.db.tables.pojos.SysUser, Long> {

    /**
     * Create a new SysUserDao without any configuration
     */
    public SysUserDao() {
        super(SysUser.SYS_USER, com.xzh.myresrc.admin.db.tables.pojos.SysUser.class);
    }

    /**
     * Create a new SysUserDao with an attached configuration
     */
    @Autowired
    public SysUserDao(Configuration configuration) {
        super(SysUser.SYS_USER, com.xzh.myresrc.admin.db.tables.pojos.SysUser.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(com.xzh.myresrc.admin.db.tables.pojos.SysUser object) {
        return object.getUserId();
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<com.xzh.myresrc.admin.db.tables.pojos.SysUser> fetchByUserId(Long... values) {
        return fetch(SysUser.SYS_USER.USER_ID, values);
    }

    /**
     * Fetch a unique record that has <code>user_id = value</code>
     */
    public com.xzh.myresrc.admin.db.tables.pojos.SysUser fetchOneByUserId(Long value) {
        return fetchOne(SysUser.SYS_USER.USER_ID, value);
    }

    /**
     * Fetch records that have <code>username IN (values)</code>
     */
    public List<com.xzh.myresrc.admin.db.tables.pojos.SysUser> fetchByUsername(String... values) {
        return fetch(SysUser.SYS_USER.USERNAME, values);
    }

    /**
     * Fetch a unique record that has <code>username = value</code>
     */
    public com.xzh.myresrc.admin.db.tables.pojos.SysUser fetchOneByUsername(String value) {
        return fetchOne(SysUser.SYS_USER.USERNAME, value);
    }

    /**
     * Fetch records that have <code>password IN (values)</code>
     */
    public List<com.xzh.myresrc.admin.db.tables.pojos.SysUser> fetchByPassword(String... values) {
        return fetch(SysUser.SYS_USER.PASSWORD, values);
    }

    /**
     * Fetch records that have <code>salt IN (values)</code>
     */
    public List<com.xzh.myresrc.admin.db.tables.pojos.SysUser> fetchBySalt(String... values) {
        return fetch(SysUser.SYS_USER.SALT, values);
    }

    /**
     * Fetch records that have <code>email IN (values)</code>
     */
    public List<com.xzh.myresrc.admin.db.tables.pojos.SysUser> fetchByEmail(String... values) {
        return fetch(SysUser.SYS_USER.EMAIL, values);
    }

    /**
     * Fetch records that have <code>mobile IN (values)</code>
     */
    public List<com.xzh.myresrc.admin.db.tables.pojos.SysUser> fetchByMobile(String... values) {
        return fetch(SysUser.SYS_USER.MOBILE, values);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<com.xzh.myresrc.admin.db.tables.pojos.SysUser> fetchByStatus(Integer... values) {
        return fetch(SysUser.SYS_USER.STATUS, values);
    }

    /**
     * Fetch records that have <code>create_user_id IN (values)</code>
     */
    public List<com.xzh.myresrc.admin.db.tables.pojos.SysUser> fetchByCreateUserId(Long... values) {
        return fetch(SysUser.SYS_USER.CREATE_USER_ID, values);
    }

    /**
     * Fetch records that have <code>create_time IN (values)</code>
     */
    public List<com.xzh.myresrc.admin.db.tables.pojos.SysUser> fetchByCreateTime(LocalDateTime... values) {
        return fetch(SysUser.SYS_USER.CREATE_TIME, values);
    }
}
