/*
 * This file is generated by jOOQ.
 */
package com.xzh.myresrc.admin.db.tables.daos;


import com.xzh.myresrc.admin.db.tables.SysUserToken;
import com.xzh.myresrc.admin.db.tables.records.SysUserTokenRecord;

import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * 系统用户Token
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class SysUserTokenDao extends DAOImpl<SysUserTokenRecord, com.xzh.myresrc.admin.db.tables.pojos.SysUserToken, Long> {

    /**
     * Create a new SysUserTokenDao without any configuration
     */
    public SysUserTokenDao() {
        super(SysUserToken.SYS_USER_TOKEN, com.xzh.myresrc.admin.db.tables.pojos.SysUserToken.class);
    }

    /**
     * Create a new SysUserTokenDao with an attached configuration
     */
    @Autowired
    public SysUserTokenDao(Configuration configuration) {
        super(SysUserToken.SYS_USER_TOKEN, com.xzh.myresrc.admin.db.tables.pojos.SysUserToken.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(com.xzh.myresrc.admin.db.tables.pojos.SysUserToken object) {
        return object.getUserId();
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<com.xzh.myresrc.admin.db.tables.pojos.SysUserToken> fetchByUserId(Long... values) {
        return fetch(SysUserToken.SYS_USER_TOKEN.USER_ID, values);
    }

    /**
     * Fetch a unique record that has <code>user_id = value</code>
     */
    public com.xzh.myresrc.admin.db.tables.pojos.SysUserToken fetchOneByUserId(Long value) {
        return fetchOne(SysUserToken.SYS_USER_TOKEN.USER_ID, value);
    }

    /**
     * Fetch records that have <code>token IN (values)</code>
     */
    public List<com.xzh.myresrc.admin.db.tables.pojos.SysUserToken> fetchByToken(String... values) {
        return fetch(SysUserToken.SYS_USER_TOKEN.TOKEN, values);
    }

    /**
     * Fetch a unique record that has <code>token = value</code>
     */
    public com.xzh.myresrc.admin.db.tables.pojos.SysUserToken fetchOneByToken(String value) {
        return fetchOne(SysUserToken.SYS_USER_TOKEN.TOKEN, value);
    }

    /**
     * Fetch records that have <code>expire_time IN (values)</code>
     */
    public List<com.xzh.myresrc.admin.db.tables.pojos.SysUserToken> fetchByExpireTime(LocalDateTime... values) {
        return fetch(SysUserToken.SYS_USER_TOKEN.EXPIRE_TIME, values);
    }

    /**
     * Fetch records that have <code>update_time IN (values)</code>
     */
    public List<com.xzh.myresrc.admin.db.tables.pojos.SysUserToken> fetchByUpdateTime(LocalDateTime... values) {
        return fetch(SysUserToken.SYS_USER_TOKEN.UPDATE_TIME, values);
    }
}
