/*
 * This file is generated by jOOQ.
 */
package com.xzh.myresrc.admin.db.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * 系统日志
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysLog implements Serializable {

    private static final long serialVersionUID = -759245819;

    private Long          id;
    private String        username;
    private String        operation;
    private String        method;
    private String        params;
    private Long          time;
    private String        ip;
    private LocalDateTime createDate;

    public SysLog() {}

    public SysLog(SysLog value) {
        this.id = value.id;
        this.username = value.username;
        this.operation = value.operation;
        this.method = value.method;
        this.params = value.params;
        this.time = value.time;
        this.ip = value.ip;
        this.createDate = value.createDate;
    }

    public SysLog(
        Long          id,
        String        username,
        String        operation,
        String        method,
        String        params,
        Long          time,
        String        ip,
        LocalDateTime createDate
    ) {
        this.id = id;
        this.username = username;
        this.operation = operation;
        this.method = method;
        this.params = params;
        this.time = time;
        this.ip = ip;
        this.createDate = createDate;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getOperation() {
        return this.operation;
    }

    public void setOperation(String operation) {
        this.operation = operation;
    }

    public String getMethod() {
        return this.method;
    }

    public void setMethod(String method) {
        this.method = method;
    }

    public String getParams() {
        return this.params;
    }

    public void setParams(String params) {
        this.params = params;
    }

    public Long getTime() {
        return this.time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

    public String getIp() {
        return this.ip;
    }

    public void setIp(String ip) {
        this.ip = ip;
    }

    public LocalDateTime getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(LocalDateTime createDate) {
        this.createDate = createDate;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SysLog (");

        sb.append(id);
        sb.append(", ").append(username);
        sb.append(", ").append(operation);
        sb.append(", ").append(method);
        sb.append(", ").append(params);
        sb.append(", ").append(time);
        sb.append(", ").append(ip);
        sb.append(", ").append(createDate);

        sb.append(")");
        return sb.toString();
    }
}
