/*
 * This file is generated by jOOQ.
 */
package com.xzh.myresrc.admin.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * 菜单管理
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysMenu implements Serializable {

    private static final long serialVersionUID = 844660636;

    private Long    menuId;
    private Long    parentId;
    private String  name;
    private String  url;
    private String  perms;
    private Integer type;
    private String  icon;
    private Integer orderNum;

    public SysMenu() {}

    public SysMenu(SysMenu value) {
        this.menuId = value.menuId;
        this.parentId = value.parentId;
        this.name = value.name;
        this.url = value.url;
        this.perms = value.perms;
        this.type = value.type;
        this.icon = value.icon;
        this.orderNum = value.orderNum;
    }

    public SysMenu(
        Long    menuId,
        Long    parentId,
        String  name,
        String  url,
        String  perms,
        Integer type,
        String  icon,
        Integer orderNum
    ) {
        this.menuId = menuId;
        this.parentId = parentId;
        this.name = name;
        this.url = url;
        this.perms = perms;
        this.type = type;
        this.icon = icon;
        this.orderNum = orderNum;
    }

    public Long getMenuId() {
        return this.menuId;
    }

    public void setMenuId(Long menuId) {
        this.menuId = menuId;
    }

    public Long getParentId() {
        return this.parentId;
    }

    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getPerms() {
        return this.perms;
    }

    public void setPerms(String perms) {
        this.perms = perms;
    }

    public Integer getType() {
        return this.type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public String getIcon() {
        return this.icon;
    }

    public void setIcon(String icon) {
        this.icon = icon;
    }

    public Integer getOrderNum() {
        return this.orderNum;
    }

    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SysMenu (");

        sb.append(menuId);
        sb.append(", ").append(parentId);
        sb.append(", ").append(name);
        sb.append(", ").append(url);
        sb.append(", ").append(perms);
        sb.append(", ").append(type);
        sb.append(", ").append(icon);
        sb.append(", ").append(orderNum);

        sb.append(")");
        return sb.toString();
    }
}
