/*
 * This file is generated by jOOQ.
 */
package com.xzh.myresrc.admin.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * 角色与菜单对应关系
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysRoleMenu implements Serializable {

    private static final long serialVersionUID = -6586477;

    private Long id;
    private Long roleId;
    private Long menuId;

    public SysRoleMenu() {}

    public SysRoleMenu(SysRoleMenu value) {
        this.id = value.id;
        this.roleId = value.roleId;
        this.menuId = value.menuId;
    }

    public SysRoleMenu(
        Long id,
        Long roleId,
        Long menuId
    ) {
        this.id = id;
        this.roleId = roleId;
        this.menuId = menuId;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getRoleId() {
        return this.roleId;
    }

    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    public Long getMenuId() {
        return this.menuId;
    }

    public void setMenuId(Long menuId) {
        this.menuId = menuId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SysRoleMenu (");

        sb.append(id);
        sb.append(", ").append(roleId);
        sb.append(", ").append(menuId);

        sb.append(")");
        return sb.toString();
    }
}
