/*
 * This file is generated by jOOQ.
 */
package com.xzh.myresrc.admin.db.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * 系统用户Token
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysUserToken implements Serializable {

    private static final long serialVersionUID = -257615975;

    private Long          userId;
    private String        token;
    private LocalDateTime expireTime;
    private LocalDateTime updateTime;

    public SysUserToken() {}

    public SysUserToken(SysUserToken value) {
        this.userId = value.userId;
        this.token = value.token;
        this.expireTime = value.expireTime;
        this.updateTime = value.updateTime;
    }

    public SysUserToken(
        Long          userId,
        String        token,
        LocalDateTime expireTime,
        LocalDateTime updateTime
    ) {
        this.userId = userId;
        this.token = token;
        this.expireTime = expireTime;
        this.updateTime = updateTime;
    }

    public Long getUserId() {
        return this.userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getToken() {
        return this.token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public LocalDateTime getExpireTime() {
        return this.expireTime;
    }

    public void setExpireTime(LocalDateTime expireTime) {
        this.expireTime = expireTime;
    }

    public LocalDateTime getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SysUserToken (");

        sb.append(userId);
        sb.append(", ").append(token);
        sb.append(", ").append(expireTime);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }
}
