/*
 * This file is generated by jOOQ.
 */
package com.xzh.myresrc.admin.db.tables;


import com.xzh.myresrc.admin.db.Indexes;
import com.xzh.myresrc.admin.db.Keys;
import com.xzh.myresrc.admin.db.MyresrcAdmin;
import com.xzh.myresrc.admin.db.tables.records.SysUserTokenRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 系统用户Token
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysUserToken extends TableImpl<SysUserTokenRecord> {

    private static final long serialVersionUID = -1115941506;

    /**
     * The reference instance of <code>myresrc_admin.sys_user_token</code>
     */
    public static final SysUserToken SYS_USER_TOKEN = new SysUserToken();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SysUserTokenRecord> getRecordType() {
        return SysUserTokenRecord.class;
    }

    /**
     * The column <code>myresrc_admin.sys_user_token.user_id</code>.
     */
    public final TableField<SysUserTokenRecord, Long> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>myresrc_admin.sys_user_token.token</code>. token
     */
    public final TableField<SysUserTokenRecord, String> TOKEN = createField("token", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "token");

    /**
     * The column <code>myresrc_admin.sys_user_token.expire_time</code>. 过期时间
     */
    public final TableField<SysUserTokenRecord, LocalDateTime> EXPIRE_TIME = createField("expire_time", org.jooq.impl.SQLDataType.LOCALDATETIME, this, "过期时间");

    /**
     * The column <code>myresrc_admin.sys_user_token.update_time</code>. 更新时间
     */
    public final TableField<SysUserTokenRecord, LocalDateTime> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.LOCALDATETIME, this, "更新时间");

    /**
     * Create a <code>myresrc_admin.sys_user_token</code> table reference
     */
    public SysUserToken() {
        this(DSL.name("sys_user_token"), null);
    }

    /**
     * Create an aliased <code>myresrc_admin.sys_user_token</code> table reference
     */
    public SysUserToken(String alias) {
        this(DSL.name(alias), SYS_USER_TOKEN);
    }

    /**
     * Create an aliased <code>myresrc_admin.sys_user_token</code> table reference
     */
    public SysUserToken(Name alias) {
        this(alias, SYS_USER_TOKEN);
    }

    private SysUserToken(Name alias, Table<SysUserTokenRecord> aliased) {
        this(alias, aliased, null);
    }

    private SysUserToken(Name alias, Table<SysUserTokenRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("系统用户Token"));
    }

    public <O extends Record> SysUserToken(Table<O> child, ForeignKey<O, SysUserTokenRecord> key) {
        super(child, key, SYS_USER_TOKEN);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return MyresrcAdmin.MYRESRC_ADMIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.SYS_USER_TOKEN_PRIMARY, Indexes.SYS_USER_TOKEN_TOKEN);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SysUserTokenRecord> getPrimaryKey() {
        return Keys.KEY_SYS_USER_TOKEN_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SysUserTokenRecord>> getKeys() {
        return Arrays.<UniqueKey<SysUserTokenRecord>>asList(Keys.KEY_SYS_USER_TOKEN_PRIMARY, Keys.KEY_SYS_USER_TOKEN_TOKEN);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysUserToken as(String alias) {
        return new SysUserToken(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysUserToken as(Name alias) {
        return new SysUserToken(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SysUserToken rename(String name) {
        return new SysUserToken(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SysUserToken rename(Name name) {
        return new SysUserToken(name, null);
    }
}
