/*
 * This file is generated by jOOQ.
 */
package com.xzh.myresrc.base.db.tables.daos;


import com.xzh.myresrc.base.db.tables.SysDict;
import com.xzh.myresrc.base.db.tables.records.SysDictRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * 数据字典表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class SysDictDao extends DAOImpl<SysDictRecord, com.xzh.myresrc.base.db.tables.pojos.SysDict, Long> {

    /**
     * Create a new SysDictDao without any configuration
     */
    public SysDictDao() {
        super(SysDict.SYS_DICT, com.xzh.myresrc.base.db.tables.pojos.SysDict.class);
    }

    /**
     * Create a new SysDictDao with an attached configuration
     */
    @Autowired
    public SysDictDao(Configuration configuration) {
        super(SysDict.SYS_DICT, com.xzh.myresrc.base.db.tables.pojos.SysDict.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(com.xzh.myresrc.base.db.tables.pojos.SysDict object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.xzh.myresrc.base.db.tables.pojos.SysDict> fetchById(Long... values) {
        return fetch(SysDict.SYS_DICT.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.xzh.myresrc.base.db.tables.pojos.SysDict fetchOneById(Long value) {
        return fetchOne(SysDict.SYS_DICT.ID, value);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.xzh.myresrc.base.db.tables.pojos.SysDict> fetchByName(String... values) {
        return fetch(SysDict.SYS_DICT.NAME, values);
    }

    /**
     * Fetch records that have <code>type IN (values)</code>
     */
    public List<com.xzh.myresrc.base.db.tables.pojos.SysDict> fetchByType(String... values) {
        return fetch(SysDict.SYS_DICT.TYPE, values);
    }

    /**
     * Fetch records that have <code>code IN (values)</code>
     */
    public List<com.xzh.myresrc.base.db.tables.pojos.SysDict> fetchByCode(String... values) {
        return fetch(SysDict.SYS_DICT.CODE, values);
    }

    /**
     * Fetch records that have <code>value IN (values)</code>
     */
    public List<com.xzh.myresrc.base.db.tables.pojos.SysDict> fetchByValue(String... values) {
        return fetch(SysDict.SYS_DICT.VALUE, values);
    }

    /**
     * Fetch records that have <code>order_num IN (values)</code>
     */
    public List<com.xzh.myresrc.base.db.tables.pojos.SysDict> fetchByOrderNum(Integer... values) {
        return fetch(SysDict.SYS_DICT.ORDER_NUM, values);
    }

    /**
     * Fetch records that have <code>remark IN (values)</code>
     */
    public List<com.xzh.myresrc.base.db.tables.pojos.SysDict> fetchByRemark(String... values) {
        return fetch(SysDict.SYS_DICT.REMARK, values);
    }

    /**
     * Fetch records that have <code>del_flag IN (values)</code>
     */
    public List<com.xzh.myresrc.base.db.tables.pojos.SysDict> fetchByDelFlag(Integer... values) {
        return fetch(SysDict.SYS_DICT.DEL_FLAG, values);
    }
}
