/*
 * This file is generated by jOOQ.
 */
package com.xzh.myresrc.admin.db.tables.records;


import com.xzh.myresrc.admin.db.tables.SysMenu;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 菜单管理
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysMenuRecord extends UpdatableRecordImpl<SysMenuRecord> implements Record8<Long, Long, String, String, String, Integer, String, Integer> {

    private static final long serialVersionUID = 515287233;

    /**
     * Setter for <code>myresrc_admin.sys_menu.menu_id</code>.
     */
    public void setMenuId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>myresrc_admin.sys_menu.menu_id</code>.
     */
    public Long getMenuId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>myresrc_admin.sys_menu.parent_id</code>. 父菜单ID，一级菜单为0
     */
    public void setParentId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>myresrc_admin.sys_menu.parent_id</code>. 父菜单ID，一级菜单为0
     */
    public Long getParentId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>myresrc_admin.sys_menu.name</code>. 菜单名称
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>myresrc_admin.sys_menu.name</code>. 菜单名称
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>myresrc_admin.sys_menu.url</code>. 菜单URL
     */
    public void setUrl(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>myresrc_admin.sys_menu.url</code>. 菜单URL
     */
    public String getUrl() {
        return (String) get(3);
    }

    /**
     * Setter for <code>myresrc_admin.sys_menu.perms</code>. 授权(多个用逗号分隔，如：user:list,user:create)
     */
    public void setPerms(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>myresrc_admin.sys_menu.perms</code>. 授权(多个用逗号分隔，如：user:list,user:create)
     */
    public String getPerms() {
        return (String) get(4);
    }

    /**
     * Setter for <code>myresrc_admin.sys_menu.type</code>. 类型   0：目录   1：菜单   2：按钮
     */
    public void setType(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>myresrc_admin.sys_menu.type</code>. 类型   0：目录   1：菜单   2：按钮
     */
    public Integer getType() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>myresrc_admin.sys_menu.icon</code>. 菜单图标
     */
    public void setIcon(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>myresrc_admin.sys_menu.icon</code>. 菜单图标
     */
    public String getIcon() {
        return (String) get(6);
    }

    /**
     * Setter for <code>myresrc_admin.sys_menu.order_num</code>. 排序
     */
    public void setOrderNum(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>myresrc_admin.sys_menu.order_num</code>. 排序
     */
    public Integer getOrderNum() {
        return (Integer) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, Long, String, String, String, Integer, String, Integer> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, Long, String, String, String, Integer, String, Integer> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return SysMenu.SYS_MENU.MENU_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return SysMenu.SYS_MENU.PARENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return SysMenu.SYS_MENU.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return SysMenu.SYS_MENU.URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return SysMenu.SYS_MENU.PERMS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return SysMenu.SYS_MENU.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return SysMenu.SYS_MENU.ICON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return SysMenu.SYS_MENU.ORDER_NUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getMenuId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getParentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getPerms();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getIcon();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getOrderNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getMenuId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getParentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getPerms();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getIcon();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getOrderNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysMenuRecord value1(Long value) {
        setMenuId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysMenuRecord value2(Long value) {
        setParentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysMenuRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysMenuRecord value4(String value) {
        setUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysMenuRecord value5(String value) {
        setPerms(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysMenuRecord value6(Integer value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysMenuRecord value7(String value) {
        setIcon(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysMenuRecord value8(Integer value) {
        setOrderNum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SysMenuRecord values(Long value1, Long value2, String value3, String value4, String value5, Integer value6, String value7, Integer value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SysMenuRecord
     */
    public SysMenuRecord() {
        super(SysMenu.SYS_MENU);
    }

    /**
     * Create a detached, initialised SysMenuRecord
     */
    public SysMenuRecord(Long menuId, Long parentId, String name, String url, String perms, Integer type, String icon, Integer orderNum) {
        super(SysMenu.SYS_MENU);

        set(0, menuId);
        set(1, parentId);
        set(2, name);
        set(3, url);
        set(4, perms);
        set(5, type);
        set(6, icon);
        set(7, orderNum);
    }
}
